### ISSUE TITLE
there is an underflow in the right side of the page

### ISSUE THREAD

**Issue by RajeevDash007** [Wervice/wervice.github.io#5]
assign me this issue so that I can fix it. @Palmonda @Wervice 
![Wervice-Special-open-source-software](https://github.com/Wervice/wervice.github.io/assets/96860040/d88318ff-5ae3-48cf-9c2e-3f107604488d)
t.

**Comment by Wervice** [comment]
Please dont get me wrong, but, what do you mean with an underflow?
