### ISSUE TITLE
add hover to these buttons

### ISSUE THREAD

**Issue by RajeevDash007** [Wervice/wervice.github.io#6]
assign me this.
![Wervice-Special-open-source-software (1)](https://github.com/Wervice/wervice.github.io/assets/96860040/f15752d3-7dab-4e5b-8660-bdcb036ee295)

**Comment by Wervice** [comment]
I'll add a hover.

**Comment by Wervice** [comment]
They are in Lumos. right?

**Comment by Wervice** [comment]
Added one.

**Comment by Wervice** [comment]
Thank you :+1:
