### ISSUE TITLE
Archon content with large devices

### ISSUE THREAD

**Issue by ahmed-abohmaid** [Wervice/wervice.github.io#7]
Showing two cards on large devices instead of one and on small devices, it returns to one card again.

### Before
![image](https://github.com/Wervice/wervice.github.io/assets/109979191/332829a9-f326-48cc-bc2a-13d85ab73e52)

### After
![image](https://github.com/Wervice/wervice.github.io/assets/109979191/9ba39c69-7e93-4fea-8833-f8536bbc4ccb)

**Comment by Wervice** [comment]
Thank you 👍
